Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.network :public_network

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
    vb.name = 'hadoop_worker2'
  end

  ssh_pub_key = File.readlines("/home/zem/.ssh/id_rsa.pub").first.strip

  config.vm.provision "shell", inline: <<-SHELL
    echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    echo "%wheel  ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers
  SHELL

end
